// Room data + rates for the IBE list view
window.ROOMS = [
  {
    id: 107,
    name: "Dvoulůžkový pokoj Deluxe",
    number: "107",
    image: "assets/room-1.png",
    beds: "King size postel",
    capacity: "2+2",
    size: 30,
    view: "Výhled do zahrady",
    tags: ["Deluxe", "Snídaně"],
    amenities: ["King size postel", "Televize", "Sprchový kout", "WiFi zdarma", "Pracovní stůl", "Telefon", "Klimatizace"],
    note: "Máme už jen 1.",
    remaining: 1,
    rates: [
      {
        id: "deluxe-flex",
        name: "Flexibilní cena",
        meal: "Snídaně v ceně",
        cancellation: "Zrušení zdarma do 19. dubna 2026",
        cancellable: true,
        price: 4900,
        originalPrice: null,
        badge: null,
      },
      {
        id: "deluxe-nrf",
        name: "Nevratná cena",
        meal: "Volitelná strava",
        cancellation: "Nelze stornovat",
        cancellable: false,
        price: 4200,
        originalPrice: 4900,
        badge: "Nejvýhodnější",
      },
    ],
  },
  {
    id: 201,
    name: "Dvoulůžkový pokoj Executive",
    number: "201",
    image: "assets/room-2.png",
    beds: "King size postel + rozkládací",
    capacity: "2+2",
    size: 38,
    view: "Výhled do parku",
    tags: ["Executive", "Snídaně"],
    amenities: ["King size postel", "Vana + sprchový kout", "Smart TV", "WiFi zdarma", "Mini-bar", "Trezor", "Klimatizace"],
    note: null,
    remaining: null,
    rates: [
      {
        id: "exec-flex",
        name: "Flexibilní cena",
        meal: "Snídaně v ceně",
        cancellation: "Zrušení zdarma do 19. dubna 2026",
        cancellable: true,
        price: 5800,
        originalPrice: null,
        badge: null,
      },
      {
        id: "exec-half",
        name: "Polopenze",
        meal: "Snídaně + večeře",
        cancellation: "Zrušení zdarma do 12. dubna 2026",
        cancellable: true,
        price: 6900,
        originalPrice: null,
        badge: null,
      },
      {
        id: "exec-nrf",
        name: "Nevratná cena",
        meal: "Snídaně v ceně",
        cancellation: "Nelze stornovat",
        cancellable: false,
        price: 5100,
        originalPrice: 5800,
        badge: "Nejvýhodnější",
      },
    ],
  },
  {
    id: 301,
    name: "Rodinný apartmán",
    number: "301",
    image: "assets/room-3.png",
    beds: "King size + 2 lůžka",
    capacity: "2+2",
    size: 52,
    view: "Boční výhled",
    tags: ["Apartmán", "Snídaně"],
    amenities: ["2 ložnice", "Obývací prostor", "Vana + sprchový kout", "Smart TV", "Kuchyňka", "WiFi zdarma", "Klimatizace"],
    note: "Vhodný pro rodiny s dětmi",
    remaining: 3,
    rates: [
      {
        id: "fam-flex",
        name: "Flexibilní cena",
        meal: "Snídaně v ceně",
        cancellation: "Zrušení zdarma do 19. dubna 2026",
        cancellable: true,
        price: 7400,
        originalPrice: null,
        badge: null,
      },
      {
        id: "fam-nrf",
        name: "Nevratná cena",
        meal: "Snídaně v ceně",
        cancellation: "Nelze stornovat",
        cancellable: false,
        price: 6500,
        originalPrice: 7400,
        badge: "Nejvýhodnější",
      },
    ],
  },
  {
    id: 401,
    name: "Junior Suite",
    number: "401",
    image: "assets/room-1.png",
    beds: "King size + pohovka",
    capacity: "2+1",
    size: 44,
    view: "Výhled na náměstí",
    tags: ["Suite"],
    amenities: ["King size postel", "Obývací kout", "Vana", "Smart TV", "Espresso kávovar", "Mini-bar", "Klimatizace"],
    note: null,
    remaining: null,
    soldOut: true,
    rates: [],
  },
  {
    id: 501,
    name: "Dvoulůžkový pokoj Standard",
    number: "501",
    image: "assets/room-2.png",
    beds: "Twin postele",
    capacity: "2",
    size: 22,
    view: "Vnitroblok",
    tags: ["Standard"],
    amenities: ["2× samostatné lůžko", "Televize", "Sprchový kout", "WiFi zdarma", "Pracovní stůl"],
    note: null,
    remaining: 5,
    rates: [
      {
        id: "std-flex",
        name: "Flexibilní cena",
        meal: "Snídaně v ceně",
        cancellation: "Zrušení zdarma do 19. dubna 2026",
        cancellable: true,
        price: 3600,
        originalPrice: null,
        badge: null,
      },
      {
        id: "std-nrf",
        name: "Nevratná cena",
        meal: "Volitelná strava",
        cancellation: "Nelze stornovat",
        cancellable: false,
        price: 3100,
        originalPrice: 3600,
        badge: "Nejvýhodnější",
      },
    ],
  },
];

window.NIGHTS = 2;
window.GUESTS = "2 dospělí";
