// Apartment locations across Prague for the Map view.
// Each apartment is a roomtype at a specific building. Multiple apartments can
// share a building (same coords) — these form natural clusters on the map.
//
// Coords are in the map's internal coordinate system (0..1000 wide × 0..800 tall),
// matching the Prague illustration SVG below.

window.APARTMENTS = [
  // — Staré Město (2 apartments at the same building) —
  {
    id: "ap-staromak-1",
    name: "Apartmán Dlouhá – Loft",
    buildingId: "staromak-dlouha",
    building: "Dlouhá 12, Praha 1",
    neighborhood: "Staré Město",
    distance: "3 min pěšky · Staroměstské nám.",
    coords: { x: 514, y: 388 },
    image: "assets/room-1.png",
    beds: "King size + rozkládací",
    capacity: "2+2",
    size: 42,
    floor: "Podkroví · výtah",
    tags: ["Apartmán", "Snídaně v kavárně"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka & sušička", "Smart TV 55\"", "WiFi 600 Mbps", "Klimatizace", "Nespresso"],
    rating: 4.91,
    reviews: 248,
    badge: "Nejoblíbenější",
    rates: [
      { id: "dl-flex", name: "Flexibilní cena", meal: "Snídaně v kavárně", cancellable: true, price: 5900, originalPrice: null, badge: null },
      { id: "dl-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 4900, originalPrice: 5900, badge: "Nejvýhodnější" },
    ],
  },
  {
    id: "ap-staromak-2",
    name: "Apartmán Dlouhá – Studio",
    buildingId: "staromak-dlouha",
    building: "Dlouhá 12, Praha 1",
    neighborhood: "Staré Město",
    distance: "3 min pěšky · Staroměstské nám.",
    coords: { x: 514, y: 388 },
    image: "assets/room-2.png",
    beds: "Queen postel",
    capacity: "2",
    size: 28,
    floor: "2. patro · výtah",
    tags: ["Studio"],
    amenities: ["Queen postel", "Kuchyňský kout", "Smart TV", "WiFi 600 Mbps", "Klimatizace", "Espresso"],
    rating: 4.84,
    reviews: 162,
    rates: [
      { id: "dls-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4200, originalPrice: null, badge: null },
      { id: "dls-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3500, originalPrice: 4200, badge: "Nejvýhodnější" },
    ],
  },

  // — Vinohrady (3 apartments, same building near Náměstí Míru) —
  {
    id: "ap-vinohrady-1",
    name: "Apartmán Anglická – Park View",
    buildingId: "vinohrady-anglicka",
    building: "Anglická 8, Praha 2",
    neighborhood: "Vinohrady · Nám. Míru",
    distance: "2 min · metro A Náměstí Míru",
    coords: { x: 642, y: 498 },
    image: "assets/room-3.png",
    beds: "King size",
    capacity: "2+1",
    size: 56,
    floor: "4. patro · výtah",
    tags: ["Apartmán", "Výhled do parku"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka", "Smart TV", "WiFi", "Klimatizace", "Balkon"],
    rating: 4.96,
    reviews: 311,
    badge: "Superhost",
    rates: [
      { id: "vi1-flex", name: "Flexibilní cena", meal: "Snídaně v ceně", cancellable: true, price: 6400, originalPrice: null, badge: null },
      { id: "vi1-nrf", name: "Nevratná cena", meal: "Snídaně v ceně", cancellable: false, price: 5600, originalPrice: 6400, badge: "Nejvýhodnější" },
    ],
  },
  {
    id: "ap-vinohrady-2",
    name: "Apartmán Anglická – Family",
    buildingId: "vinohrady-anglicka",
    building: "Anglická 8, Praha 2",
    neighborhood: "Vinohrady · Nám. Míru",
    distance: "2 min · metro A Náměstí Míru",
    coords: { x: 642, y: 498 },
    image: "assets/room-1.png",
    beds: "King size + 2 lůžka",
    capacity: "4",
    size: 72,
    floor: "3. patro · výtah",
    tags: ["Apartmán", "Pro rodiny"],
    amenities: ["2 ložnice", "Plně vybavená kuchyň", "Pračka", "Smart TV", "WiFi", "Klimatizace", "Dětská postýlka"],
    rating: 4.89,
    reviews: 198,
    rates: [
      { id: "vi2-flex", name: "Flexibilní cena", meal: "Snídaně v ceně", cancellable: true, price: 8400, originalPrice: null, badge: null },
      { id: "vi2-nrf", name: "Nevratná cena", meal: "Snídaně v ceně", cancellable: false, price: 7300, originalPrice: 8400, badge: "Nejvýhodnější" },
    ],
  },
  {
    id: "ap-vinohrady-3",
    name: "Apartmán Anglická – Studio",
    buildingId: "vinohrady-anglicka",
    building: "Anglická 8, Praha 2",
    neighborhood: "Vinohrady · Nám. Míru",
    distance: "2 min · metro A Náměstí Míru",
    coords: { x: 642, y: 498 },
    image: "assets/room-2.png",
    beds: "Queen postel",
    capacity: "2",
    size: 26,
    floor: "1. patro · výtah",
    tags: ["Studio"],
    amenities: ["Queen postel", "Kuchyňský kout", "Smart TV", "WiFi", "Klimatizace"],
    rating: 4.78,
    reviews: 134,
    rates: [
      { id: "vi3-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 3800, originalPrice: null, badge: null },
      { id: "vi3-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3200, originalPrice: 3800, badge: "Nejvýhodnější" },
    ],
  },

  // — Karlín (2 apartments at 2 different but close buildings) —
  {
    id: "ap-karlin-1",
    name: "Apartmán Křižíkova – Industrial",
    buildingId: "karlin-krizikova",
    building: "Křižíkova 32, Praha 8",
    neighborhood: "Karlín",
    distance: "4 min · metro B Křižíkova",
    coords: { x: 652, y: 318 },
    image: "assets/room-2.png",
    beds: "King size + pohovka",
    capacity: "2+2",
    size: 64,
    floor: "Loft · 5. patro",
    tags: ["Loft", "Designové"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka", "Smart TV 65\"", "WiFi 1 Gbps", "Klimatizace", "Pracovní kout"],
    rating: 4.93,
    reviews: 207,
    badge: "Pro pracovní pobyt",
    rates: [
      { id: "ka1-flex", name: "Flexibilní cena", meal: "Snídaně v pekárně", cancellable: true, price: 5600, originalPrice: null, badge: null },
      { id: "ka1-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 4800, originalPrice: 5600, badge: "Nejvýhodnější" },
    ],
  },
  {
    id: "ap-karlin-2",
    name: "Apartmán Sokolovská – Riverside",
    buildingId: "karlin-sokolovska",
    building: "Sokolovská 145, Praha 8",
    neighborhood: "Karlín",
    distance: "6 min · metro B Invalidovna",
    coords: { x: 705, y: 308 },
    image: "assets/room-3.png",
    beds: "Queen postel",
    capacity: "2",
    size: 36,
    floor: "3. patro · výtah",
    tags: ["Apartmán"],
    amenities: ["Queen postel", "Kuchyňka", "Pračka", "Smart TV", "WiFi", "Klimatizace"],
    rating: 4.81,
    reviews: 156,
    rates: [
      { id: "ka2-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4400, originalPrice: null, badge: null },
      { id: "ka2-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3800, originalPrice: 4400, badge: "Nejvýhodnější" },
    ],
  },

  // — Malá Strana —
  {
    id: "ap-malastrana-1",
    name: "Apartmán Malostranské nám.",
    buildingId: "malastrana-namesti",
    building: "Malostranské nám. 6, Praha 1",
    neighborhood: "Malá Strana",
    distance: "1 min · tram Malostranské nám.",
    coords: { x: 425, y: 412 },
    image: "assets/room-1.png",
    beds: "King size",
    capacity: "2",
    size: 48,
    floor: "Historický dům · 2. patro",
    tags: ["Historický dům", "Snídaně"],
    amenities: ["King size postel", "Kuchyňka", "Vana", "Smart TV", "WiFi", "Trámové stropy"],
    rating: 4.97,
    reviews: 421,
    badge: "Nejlépe hodnocené",
    rates: [
      { id: "ms-flex", name: "Flexibilní cena", meal: "Snídaně v ceně", cancellable: true, price: 7800, originalPrice: null, badge: null },
      { id: "ms-nrf", name: "Nevratná cena", meal: "Snídaně v ceně", cancellable: false, price: 6800, originalPrice: 7800, badge: "Nejvýhodnější" },
    ],
  },

  // — Žižkov (2 apartments at the same building, near Riegrovy sady) —
  {
    id: "ap-zizkov-1",
    name: "Apartmán Riegrovy sady – Park",
    buildingId: "zizkov-riegrovy",
    building: "Polská 24, Praha 2",
    neighborhood: "Vinohrady · Riegrovy sady",
    distance: "2 min · vstup do parku",
    coords: { x: 700, y: 428 },
    image: "assets/room-3.png",
    beds: "King size",
    capacity: "2+1",
    size: 52,
    floor: "4. patro · výtah · terasa",
    tags: ["Apartmán", "Terasa"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka", "Smart TV", "WiFi", "Klimatizace", "Terasa 18 m²"],
    rating: 4.95,
    reviews: 289,
    rates: [
      { id: "zi1-flex", name: "Flexibilní cena", meal: "Snídaně v ceně", cancellable: true, price: 6200, originalPrice: null, badge: null },
      { id: "zi1-nrf", name: "Nevratná cena", meal: "Snídaně v ceně", cancellable: false, price: 5400, originalPrice: 6200, badge: "Nejvýhodnější" },
    ],
  },
  {
    id: "ap-zizkov-2",
    name: "Apartmán Riegrovy sady – Cosy",
    buildingId: "zizkov-riegrovy",
    building: "Polská 24, Praha 2",
    neighborhood: "Vinohrady · Riegrovy sady",
    distance: "2 min · vstup do parku",
    coords: { x: 700, y: 428 },
    image: "assets/room-1.png",
    beds: "Queen postel",
    capacity: "2",
    size: 32,
    floor: "2. patro · výtah",
    tags: ["Studio"],
    amenities: ["Queen postel", "Kuchyňka", "Smart TV", "WiFi", "Klimatizace"],
    rating: 4.82,
    reviews: 178,
    rates: [
      { id: "zi2-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4100, originalPrice: null, badge: null },
      { id: "zi2-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3500, originalPrice: 4100, badge: "Nejvýhodnější" },
    ],
  },

  // — Smíchov · Anděl —
  {
    id: "ap-smichov-1",
    name: "Apartmán Anděl – Modern",
    buildingId: "smichov-andel",
    building: "Plzeňská 4, Praha 5",
    neighborhood: "Smíchov · Anděl",
    distance: "3 min · metro B Anděl",
    coords: { x: 332, y: 588 },
    image: "assets/room-2.png",
    beds: "King size",
    capacity: "2+1",
    size: 44,
    floor: "6. patro · výtah",
    tags: ["Apartmán", "Novostavba"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka", "Smart TV", "WiFi", "Klimatizace", "Výhled"],
    rating: 4.86,
    reviews: 192,
    rates: [
      { id: "sm-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4900, originalPrice: null, badge: null },
      { id: "sm-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 4200, originalPrice: 4900, badge: "Nejvýhodnější" },
    ],
  },

  // — Letná —
  {
    id: "ap-letna-1",
    name: "Apartmán Letná – Park",
    buildingId: "letna-kostelni",
    building: "Kostelní 5, Praha 7",
    neighborhood: "Letná · Letenské sady",
    distance: "2 min · tram Letenské nám.",
    coords: { x: 470, y: 285 },
    image: "assets/room-1.png",
    beds: "Queen postel",
    capacity: "2",
    size: 38,
    floor: "3. patro",
    tags: ["Apartmán", "Klidná lokalita"],
    amenities: ["Queen postel", "Kuchyňka", "Pračka", "Smart TV", "WiFi", "Klimatizace"],
    rating: 4.88,
    reviews: 154,
    rates: [
      { id: "le-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4600, originalPrice: null, badge: null },
      { id: "le-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3900, originalPrice: 4600, badge: "Nejvýhodnější" },
    ],
  },

  // — Holešovice —
  {
    id: "ap-holesovice-1",
    name: "Apartmán Holešovice – Loft",
    buildingId: "holesovice-veletrzni",
    building: "Veletržní 24, Praha 7",
    neighborhood: "Holešovice",
    distance: "5 min · tram Veletržní palác",
    coords: { x: 560, y: 222 },
    image: "assets/room-3.png",
    beds: "King size + rozkládací",
    capacity: "2+2",
    size: 58,
    floor: "Loft · 5. patro",
    tags: ["Loft", "Industriál"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Pračka", "Smart TV 65\"", "WiFi 1 Gbps", "Klimatizace", "Vysoké stropy"],
    rating: 4.83,
    reviews: 167,
    rates: [
      { id: "ho-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4800, originalPrice: null, badge: null },
      { id: "ho-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 4100, originalPrice: 4800, badge: "Nejvýhodnější" },
    ],
  },

  // — Nové Město · Václavské nám. —
  {
    id: "ap-vaclavak-1",
    name: "Apartmán Václavské nám.",
    buildingId: "novemesto-vaclavak",
    building: "Václavské nám. 22, Praha 1",
    neighborhood: "Nové Město · Václavské nám.",
    distance: "1 min · metro A/B Můstek",
    coords: { x: 548, y: 458 },
    image: "assets/room-2.png",
    beds: "Queen postel",
    capacity: "2",
    size: 34,
    floor: "4. patro · výtah",
    tags: ["Apartmán", "V centru"],
    amenities: ["Queen postel", "Kuchyňka", "Smart TV", "WiFi", "Klimatizace", "Zvukotěsná okna"],
    rating: 4.74,
    reviews: 312,
    rates: [
      { id: "va-flex", name: "Flexibilní cena", meal: "Self check-in", cancellable: true, price: 4400, originalPrice: null, badge: null },
      { id: "va-nrf", name: "Nevratná cena", meal: "Self check-in", cancellable: false, price: 3700, originalPrice: 4400, badge: "Nejvýhodnější" },
    ],
  },
];

// Neighborhoods used for filter chips (counts derived live).
window.APARTMENT_NEIGHBORHOODS = [
  "Staré Město",
  "Malá Strana",
  "Nové Město · Václavské nám.",
  "Vinohrady · Nám. Míru",
  "Vinohrady · Riegrovy sady",
  "Karlín",
  "Smíchov · Anděl",
  "Letná · Letenské sady",
  "Holešovice",
];
