// Long-term rental room data — monthly pricing, deposits, contract types
window.LTR_ROOMS = [
  {
    id: 301,
    name: "Studio Klid",
    number: "301",
    image: "assets/room-1.png",
    beds: "Manželská postel",
    capacity: "1-2",
    size: 28,
    view: "Vnitroblok",
    tags: ["Studio", "Tichá zóna"],
    amenities: ["Manželská postel", "Plně vybavená kuchyňka", "Pracovní stůl", "WiFi 1 Gbps", "Vlastní koupelna", "Pračka", "Klimatizace"],
    floor: 3,
    availableFrom: "1. září 2026",
    minMonths: 3,
    maxMonths: 12,
    monthlyFrom: 17500,
    deposit: 35000,
    bookingFee: 3000,
    student: true,
    petFriendly: false,
    rates: [
      { id: "std", name: "Standard nájem", monthly: 18000, sub: "Bez dlouhodobé slevy · krátký zápis", contract: "Krátkodobá smlouva 3–6 měsíců", badge: null },
      { id: "long", name: "Dlouhodobý nájem", monthly: 17500, sub: "Sleva 3 % · pro pobyt ≥ 6 měsíců", contract: "Roční smlouva s prodloužením", badge: "−3 %" },
      { id: "student", name: "Studentský nájem", monthly: 16800, sub: "Sleva 7 % · vyžaduje platný ISIC", contract: "Akademický rok, 9 měsíců", badge: "ISIC" },
    ],
  },
  {
    id: 302,
    name: "Apartmán Park",
    number: "302",
    image: "assets/room-2.png",
    beds: "King size + rozkládací pohovka",
    capacity: "1-3",
    size: 42,
    view: "Park",
    tags: ["Apartmán", "Erasmus friendly"],
    amenities: ["King size postel", "Plně vybavená kuchyň", "Obývací prostor", "Pracovní kout", "WiFi 1 Gbps", "Vana + sprchový kout", "Pračka + sušička", "Klimatizace", "Balkon"],
    floor: 5,
    availableFrom: "15. srpna 2026",
    minMonths: 3,
    maxMonths: 12,
    monthlyFrom: 24500,
    deposit: 50000,
    bookingFee: 3000,
    student: true,
    petFriendly: true,
    rates: [
      { id: "std", name: "Standard nájem", monthly: 25500, sub: "Bez dlouhodobé slevy", contract: "Krátkodobá smlouva 3–6 měsíců", badge: null },
      { id: "long", name: "Dlouhodobý nájem", monthly: 24500, sub: "Sleva 4 % · pro pobyt ≥ 6 měsíců", contract: "Roční smlouva s prodloužením", badge: "−4 %" },
    ],
  },
  {
    id: 303,
    name: "Studio Compact",
    number: "303",
    image: "assets/room-3.png",
    beds: "Rozkládací pohovka",
    capacity: "1",
    size: 22,
    view: "Ulice",
    tags: ["Pro 1 osobu", "Studentské"],
    amenities: ["Pohodlná pohovka", "Mini-kuchyňka", "Pracovní stůl", "WiFi 1 Gbps", "Vlastní sprcha"],
    floor: 2,
    availableFrom: "1. září 2026",
    minMonths: 3,
    maxMonths: 12,
    monthlyFrom: 13900,
    deposit: 28000,
    bookingFee: 2000,
    student: true,
    petFriendly: false,
    rates: [
      { id: "std", name: "Standard nájem", monthly: 14500, sub: "Krátkodobá flexibilita", contract: "3–6 měsíců", badge: null },
      { id: "long", name: "Dlouhodobý nájem", monthly: 13900, sub: "Sleva 4 %", contract: "Roční smlouva", badge: "−4 %" },
      { id: "student", name: "Studentský nájem", monthly: 12500, sub: "ISIC sleva 14 %", contract: "Akademický rok", badge: "ISIC" },
    ],
  },
  {
    id: 304,
    name: "Penthouse Skyline",
    number: "304",
    image: "assets/room-1.png",
    beds: "King size + 2 lůžka",
    capacity: "2-4",
    size: 78,
    view: "Panorama Prahy",
    tags: ["Premium", "Pro páry / sdílení"],
    amenities: ["2 ložnice", "Plně vybavená kuchyň", "Velký obývák", "2 koupelny", "Velká terasa", "WiFi 1 Gbps", "Klimatizace", "Pračka + sušička"],
    floor: 7,
    availableFrom: "1. července 2026",
    minMonths: 6,
    maxMonths: 24,
    monthlyFrom: 46000,
    deposit: 92000,
    bookingFee: 4000,
    student: false,
    petFriendly: true,
    rates: [
      { id: "std", name: "Standard nájem", monthly: 48000, sub: "Krátkodobá smlouva", contract: "6 měsíců min.", badge: null },
      { id: "long", name: "Dlouhodobý nájem", monthly: 46000, sub: "Sleva 4 %", contract: "Roční smlouva s opcí", badge: "−4 %" },
    ],
  },
];

// Per-month pricing variation (energy + season multipliers)
// Used for monthly breakdown
window.LTR_MONTHS = [
  { month: 8, name: "Srpen 2026",   factor: 1.00 },
  { month: 9, name: "Září 2026",    factor: 1.00 },
  { month: 10, name: "Říjen 2026",  factor: 1.04 },
  { month: 11, name: "Listopad 2026", factor: 1.08 },
  { month: 12, name: "Prosinec 2026", factor: 1.10 },
  { month: 1, name: "Leden 2027",   factor: 1.10 },
  { month: 2, name: "Únor 2027",    factor: 1.08 },
  { month: 3, name: "Březen 2027",  factor: 1.04 },
  { month: 4, name: "Duben 2027",   factor: 1.00 },
  { month: 5, name: "Květen 2027",  factor: 0.96 },
  { month: 6, name: "Červen 2027",  factor: 0.96 },
  { month: 7, name: "Červenec 2027", factor: 0.96 },
];
