// Package data — bundled experiences. Anti-OTA: emotional copy, what's included, savings.
window.PACKAGES = [
  {
    id: "romantic",
    name: "Romantický víkend pro zamilované",
    tagline: "2 noci v Deluxe pokoji · sekt · večeře při svíčkách",
    description: "Strávte víkend ve dvou. Připravíme vám pokoj se sektem a růžemi, večeři při svíčkách a wellness pro páry.",
    image: "assets/room-3.png",
    nights: 2,
    badge: "Bestseller",
    tags: ["Pro páry", "Wellness", "Snídaně"],
    inclusions: [
      "2 noci v pokoji Deluxe nebo Executive",
      "Bohatá snídaně na pokoj",
      "Lahev sektu Bohemia + ovoce + růže",
      "3-chodová večeře při svíčkách",
      "60 min wellness pro 2 osoby (sauna + vířivka)",
      "Pozdní check-out do 14:00",
    ],
    fromPrice: 7200,
    originalPrice: 9400,
    savings: 2200,
    minNights: 2,
  },
  {
    id: "wellness",
    name: "Wellness pobyt s plnou regenerací",
    tagline: "3 noci · neomezený wellness · 2 procedury / osoba",
    description: "Komplexní detox a relaxace. Neomezený přístup do hotelového wellness a dvě procedury podle vašeho výběru.",
    image: "assets/room-2.png",
    nights: 3,
    badge: "Top výběr",
    tags: ["Wellness", "Polopenze", "Procedury"],
    inclusions: [
      "3 noci v pokoji Deluxe",
      "Polopenze v hotelové restauraci",
      "Neomezený wellness (sauna, pára, vířivka, bazén)",
      "2× procedura podle výběru (masáž / zábal / peeling)",
      "Welcome drink a ovocný talíř",
      "Župan a pantofle na pokoj",
    ],
    fromPrice: 8900,
    originalPrice: 11800,
    savings: 2900,
    minNights: 3,
  },
  {
    id: "family",
    name: "Rodinný pobyt s programem pro děti",
    tagline: "2 noci · rodinný apartmán · animátoři · vstup do aquaparku",
    description: "Pohodový pobyt pro rodiny s dětmi. Animační program, dětské menu a vstupenky do nedalekého aquaparku.",
    image: "assets/room-1.png",
    nights: 2,
    badge: null,
    tags: ["Rodina", "Děti zdarma", "Aquapark"],
    inclusions: [
      "2 noci v rodinném apartmánu (2+2)",
      "Polopenze + dětské menu zdarma",
      "Vstupenky do aquaparku Babylon (4×)",
      "Animátoři pro děti 4–12 let",
      "Dětský welcome balíček",
      "Postýlka nebo dětská postel zdarma",
    ],
    fromPrice: 9600,
    originalPrice: 12100,
    savings: 2500,
    minNights: 2,
  },
  {
    id: "weekend",
    name: "Prodloužený víkend v Praze",
    tagline: "3 noci za cenu 2 · městská prohlídka v ceně",
    description: "Tři noci ve městě s prohlídkou s lokálním průvodcem a degustací v hotelovém baru.",
    image: "assets/room-2.png",
    nights: 3,
    badge: "−33 %",
    tags: ["City break", "Snídaně"],
    inclusions: [
      "3 noci za cenu 2 (3. noc zdarma)",
      "Bohatá snídaně",
      "Prohlídka města s průvodcem (3 h)",
      "Degustace lokálních vín v baru",
      "Pražská MHD karta na 72 h",
    ],
    fromPrice: 6800,
    originalPrice: 10200,
    savings: 3400,
    minNights: 3,
  },
];
