// Reviews data
window.REVIEWS_SUMMARY = {
  score: 9.2,
  scoreLabel: "Vynikající",
  totalReviews: 1847,
  recommendPct: 96,
  sources: [
    { name: "Booking.com", score: 9.3, count: 912, color: "#003580" },
    { name: "Google", score: 4.7, max: 5, count: 654, color: "#4285F4" },
    { name: "Tripadvisor", score: 4.8, max: 5, count: 281, color: "#00AA6C" },
  ],
  categories: [
    { label: "Personál", score: 9.6 },
    { label: "Čistota", score: 9.5 },
    { label: "Komfort", score: 9.3 },
    { label: "Lokalita", score: 9.4 },
    { label: "Snídaně", score: 9.1 },
    { label: "Wellness", score: 8.9 },
    { label: "Hodnota za peníze", score: 8.7 },
    { label: "Wi-Fi zdarma", score: 9.7 },
  ],
};

window.REVIEWS = [
  {
    id: 1, name: "Jana K.", initials: "JK", country: "Česko", flag: "🇨🇿",
    date: "12. dubna 2026", stayType: "Pár · 2 noci", room: "Dvoulůžkový pokoj Deluxe",
    score: 9.6, source: "Booking.com",
    title: "Skvělý víkend pro dva",
    body: "Přivítali nás welcome drinkem a personál byl po celou dobu pobytu velmi vstřícný. Pokoj byl čistý a moderní, snídaně bohatá. Určitě se vrátíme.",
    pros: "Přátelský personál, výborná snídaně, klid",
    cons: "Slabší tlak ve sprše",
    reply: "Děkujeme za milé hodnocení! Na tlaku ve sprše už pracujeme — pokoj 107 jsme zařadili do plánu rekonstrukce na podzim. Těšíme se na Vás příště. — Recepce",
  },
  {
    id: 2, name: "Martin H.", initials: "MH", country: "Slovensko", flag: "🇸🇰",
    date: "8. dubna 2026", stayType: "Rodina · 3 noci", room: "Rodinný apartmán",
    score: 9.8, source: "Booking.com",
    title: "Ideální pro rodiny s dětmi",
    body: "Apartmán byl prostorný a děti měly k dispozici dětský koutek. Personál nám ochotně přichystal i pozdní snídani. Kuchyňka skvěle posloužila.",
    pros: "Velký prostor, dětské vybavení, ochotný personál",
    cons: null,
    reply: null,
  },
  {
    id: 3, name: "Eva P.", initials: "EP", country: "Rakousko", flag: "🇦🇹",
    date: "3. dubna 2026", stayType: "Pracovní cesta · 1 noc", room: "Dvoulůžkový pokoj Executive",
    score: 9.4, source: "Google",
    title: "Vynikající business pobyt",
    body: "Wi-Fi rychlá, pracovní stůl velký, klimatizace tichá. Recepce 24/7 mi pomohla i s pozdním check-inem v 1 ráno. Doporučuji všem na služebky.",
    pros: "Rychlá Wi-Fi, tichý pokoj, recepce 24/7",
    cons: "Restaurace v neděli zavřená",
    reply: null,
  },
  {
    id: 4, name: "Tomáš R.", initials: "TR", country: "Česko", flag: "🇨🇿",
    date: "28. března 2026", stayType: "Pár · 2 noci", room: "Junior Suite",
    score: 10, source: "Tripadvisor",
    title: "Nezapomenutelný romantický víkend",
    body: "Manželce jsem objednal výročí pobytu a tým hotelu vše perfektně připravil — šampaňské, růže v pokoji, večeři u krbu. Personál nadstandardní.",
    pros: "Atmosféra, romantický balíček, gastronomie",
    cons: null,
    reply: "Tomáši, velmi nás potěšilo, že jste si výročí užili právě u nás. Ať Vám láska vydrží a brzy se na další oslavu těšíme. — Tým Balický",
  },
  {
    id: 5, name: "Hana B.", initials: "HB", country: "Česko", flag: "🇨🇿",
    date: "22. března 2026", stayType: "Wellness · 2 noci", room: "Dvoulůžkový pokoj Deluxe",
    score: 8.8, source: "Booking.com",
    title: "Hezký wellness pobyt, ale parkování slabší",
    body: "Wellness zóna malá ale velmi pěkně udržovaná. Sauny příjemné, bazén v pořádku. Hotelové parkování bylo plné, museli jsme parkovat o ulici dál.",
    pros: "Saunový svět, masáže, snídaně",
    cons: "Kapacita parkování, hlučnější ulice",
    reply: "Hano, děkujeme za zpětnou vazbu. Pro hosty, kteří přijíždí autem, doporučujeme rezervovat parkování předem v rezervačním formuláři — kapacita je omezená. — Recepce",
  },
  {
    id: 6, name: "Petr S.", initials: "PS", country: "Česko", flag: "🇨🇿",
    date: "15. března 2026", stayType: "Sólo · 1 noc", room: "Dvoulůžkový pokoj Standard",
    score: 9.0, source: "Google",
    title: "Skvělá lokalita, vše po ruce",
    body: "Bydlel jsem tu během konference. Lokalita perfektní — vše v pěším dosahu. Pokoj malý ale dobře řešený, postel pohodlná.",
    pros: "Lokalita, postel, snídaně formou bufetu",
    cons: "Pokoj menší (22 m²)",
    reply: null,
  },
];
